[package]
name = "febiflow-support"
version = "0.1.0"
edition = "2024"

[dependencies]
febiflow-lambda = { workspace = true }
lambda_http = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
validator = { workspace = true }
