[package]
name = "febiflow"
version = "0.1.0"
edition = "2024"

[dependencies]
febiflow-auth = { workspace = true }
febiflow-database = { workspace = true }
febiflow-http = { workspace = true }
febiflow-lambda = { workspace = true }
febiflow-support = { workspace = true }
