[package]
name = "ferrum-lambda"
version = "0.1.0"
edition = "2024"

[dependencies]
lambda_http = "0.14.0"
serde = { version = "1.0.218", features = ["derive"] }
serde_json = "1.0.140"
sqlx = { version = "0.8" }
