[package]
name = "febiflow-auth"
version = "0.1.0"
edition = "2024"

[dependencies]
jsonwebtoken = { workspace = true }
febiflow-lambda = { workspace = true }
serde = { workspace = true }
uuid = { workspace = true }
