[package]
name = "ferrum"
version = "0.1.0"
edition = "2024"

[dependencies]
ferrum-database = { path = "../crates/ferrum-database" }
ferrum-http = { path = "../crates/ferrum-http" }
ferrum-lambda = { path = "../crates/ferrum-lambda" }
ferrum-support = { path = "../crates/ferrum-support" }
